-- upgrade --
CREATE TABLE IF NOT EXISTS `chairs` (
    `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `created_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `deleted_at` DATETIME(6)
) CHARACTER SET utf8mb4;
-- downgrade --
DROP TABLE IF EXISTS `chairs`;
