name: PR to staging

on:
  push:
    branches:
      - develop

jobs:
  pr-staging:
    name: Automatically create/update PR
    runs-on: ubuntu-latest
    needs: []
    steps:
    - uses: actions/checkout@v2.4.0
    - name: pull-request
      uses: repo-sync/pull-request@v2.6
      with:
        source_branch: "develop"                                 # If blank, default: triggered branch
        destination_branch: "staging"                      # If blank, default: master
        pr_title: "Pulling develop into staging" # Title of pull request
        # pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
        pr_reviewer: "wanted2"                         # Comma-separated list (no spaces)
        pr_assignee: "wanted2"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr,merge"                               # Comma-separated list (no spaces)
        # pr_milestone: "Milestone 1"                       # Milestone name
        pr_draft: false                                    # Creates pull request as draft
        pr_allow_empty: false                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build-docker-develop:
    name: Deploy to develop environment
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2.4.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wendy:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Notify M$ Teams
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Could not build docker image for ${{ github.sha }}"
          timezone: Asia/Tokyo
          notification-color: e3241a

      - name: Notify M$ Teams
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Updated docker container with ${{ steps.docker_build.outputs.digest }}"
          timezone: Asia/Tokyo
          notification-color: 486ee8
  
  deploy-to-azure:
    name: Deploy the docker container to M$ Azure App Services
    runs-on: ubuntu-latest
    needs: [build-docker-develop]
    environment: develop
    strategy:
      fail-fast: true
    steps:
      - name: Setup Azure CLI
        run: |
          apt update
          apt install -y ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          export AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
          apt update
          apt install -y azure-cli
          az group -h
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0
      - name: Provision the Resource Group in Azure (including WebApps, MySql, ServicePlan)
        timeout-minutes: 5
        run: |
          az group delete -g ${{ secrets.DEV_RG }}
          az group create -g ${{ secrets.DEV_RG }} -l eastus
          az deployment group create --resource-group ${{ secrets.DEV_RG }} --template-file templates/arm/develop.json --parameters "{\"siteName\": \"${{ secrets.DEV_SITENAME }}\", \"imageName\": \"${{secrets.DEV_IMAGENAME }}\", \"administratorLogin\": \"${{ secrets.DEV_MYSQL_USERNAME }}\", \"administratorLoginPassword\": \"${{ secrets.DEV_MYSQL_PASSWORD }}\"}"
      - name: Notify M$ Teams
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Couldn't provision develop environment for commit ${{ github.sha }}."
          timezone: Asia/Tokyo
          notification-color: e3241a
      - name: Notify M$ Teams
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Provisioned develop environment for commit ${{ github.sha }}. DON'T forget to delete this environment after you approve the work to avoid additional charges."
          timezone: Asia/Tokyo
          notification-color: 486ee8

  rollback-azure:
    name: Delete the provisioned environment to avoid additional charges
    strategy:
      fail-fast: 
    runs-on: ubuntu-latest
    needs: [deploy-to-azure]
    environment: develop
    steps:
      - name: Setup Azure CLI
        run: |
          apt update
          apt install -y ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          export AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
          apt update
          apt install -y azure-cli
          az group -h
      - name: Rollback
        run: |
          az group delete -g ${{ secrets.DEV_RG }}
      - name: Notify M$ Teams
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Couldn't auto-delete develop environment for commit ${{ github.sha }}. Please delete it manually."
          timezone: Asia/Tokyo
          notification-color: e3241a
      - name: Notify M$ Teams
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Provisioned develop environment for commit ${{ github.sha }} has been DELETED. DON'T forget to let the authors know your feedback!"
          timezone: Asia/Tokyo
          notification-color: 486ee8

  notify-teams:
    name: Notify M$ Teams channels
    runs-on: ubuntu-latest
    needs: [pr-staging]
    steps:
      - name: Notify M$ Teams
        uses: jdcargile/ms-teams-notification@v1.3
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAM_HOOK_URL }}
          notification-summary: "Someone merged commit ${{ github.sha }} into develop which triggered a PR to staging"
          timezone: Asia/Tokyo
          notification-color: 486ee8
